<?php
// src/SqlGen/Generator.php

namespace MySqlSchemaSync\SqlGen;

use MySqlSchemaSync\Config\Connection;
use MySqlSchemaSync\Diff\DiffResult;
use MySqlSchemaSync\Diff\StructSyncAdapter;

class Generator
{
    /** @var array<string, array> Cached diffSql when no live adapter is available */
    private array $cachedDiffSql = [];

    /**
     * @param Connection         $source   Source connection (new structure)
     * @param Connection         $target   Target connection (to be migrated)
     * @param StructSyncAdapter|null $adapter  Adapter (null when using pre-cached diffSql)
     * @param array              $diffSql  Pre-cached diffSql array (used when adapter is null)
     */
    public function __construct(
        private Connection $source,
        private Connection $target,
        private ?StructSyncAdapter $adapter = null,
        array $diffSql = [],
    ) {
        $this->cachedDiffSql = $diffSql;
    }

    public function generate(DiffResult $diff, bool $useTransaction = true): string
    {
        $diffSql = $this->adapter ? $this->adapter->getDiffSql() : $this->cachedDiffSql;
        $selectedTables = array_flip(array_column($diff->newTables, 'name'));
        $removedTables = array_flip(array_column($diff->removedTables, 'name'));

        $changedMap = [];
        foreach ($diff->changedTables as $t) {
            $changedMap[$t['name']] = $t;
        }
        $newIndexMap = [];
        foreach ($diff->newIndexes as $i) {
            $newIndexMap[$i['table']][$i['name']] = true;
        }
        $removedIndexMap = [];
        foreach ($diff->removedIndexes as $i) {
            $removedIndexMap[$i['table']][$i['name']] = true;
        }

        $lines = [];
        $lines[] = "-- Auto-generated by MySQL SchemaSync PHP Edition";
        $lines[] = "-- Source: {$this->source->name} ({$this->source->database})";
        $lines[] = "-- Target: {$this->target->name} ({$this->target->database})";
        $lines[] = "-- Generated at: " . date('Y-m-d H:i:s');
        $lines[] = "";

        if ($useTransaction) {
            $lines[] = "START TRANSACTION;";
            $lines[] = "";
        }

        foreach ($diffSql['ADD_TABLE'] ?? [] as $sql) {
            $name = preg_match('/CREATE\s+TABLE\s+`?(\w+)`?/i', $sql, $m) ? $m[1] : null;
            if ($name && isset($selectedTables[$name])) {
                $lines[] = "-- [SAFE] CREATE TABLE `{$name}`";
                $lines[] = rtrim($sql, ';') . ";";
                $lines[] = "";
            }
        }

        foreach ($diffSql['MODIFY_FIELD'] ?? [] as $table => $fields) {
            if (!isset($changedMap[$table])) continue;
            $t = $changedMap[$table];
            $lines[] = "-- === 变更表: {$table} === [{$t['risk']}]";
            foreach ($fields as $col => $def) {
                $lines[] = "ALTER TABLE `{$table}` MODIFY {$def};";
            }
            $lines[] = "";
        }

        foreach ($diffSql['ADD_FIELD'] ?? [] as $table => $fields) {
            if (!isset($changedMap[$table])) continue;
            $lines[] = "-- === 新增列: {$table} ===";
            foreach ($fields as $col => $def) {
                $lines[] = "ALTER TABLE `{$table}` ADD {$def};";
            }
            $lines[] = "";
        }

        foreach ($diffSql['DROP_FIELD'] ?? [] as $table => $fields) {
            if (!isset($changedMap[$table])) continue;
            $lines[] = "-- === 删除列: {$table} ===";
            foreach ($fields as $col => $def) {
                $lines[] = "ALTER TABLE `{$table}` DROP COLUMN `{$col}`;";
            }
            $lines[] = "";
        }

        // ADD_CONSTRAINT: diffSql contains flat ALTER TABLE SQL strings
        foreach ($diffSql['ADD_CONSTRAINT'] ?? [] as $sql) {
            if (preg_match("/^ALTER\s+TABLE\s+`(\w+)`\s+ADD\s+(?:PRIMARY\s+KEY|KEY\s+`(\w+)`)/is", $sql, $m)) {
                $table = $m[1];
                $idxName = (isset($m[2]) && $m[2] !== '') ? $m[2] : 'PRIMARY';
                if (isset($newIndexMap[$table][$idxName])) {
                    $lines[] = $sql . ';';
                }
            } elseif (preg_match("/^ALTER\s+TABLE\s+`(\w+)`\s+ADD\s+CONSTRAINT\s+`(\w+)`\s+FOREIGN\s+KEY/is", $sql, $m)) {
                $lines[] = $sql . ';';
            }
        }

        // DROP_CONSTRAINT: flat ALTER TABLE SQL strings
        foreach ($diffSql['DROP_CONSTRAINT'] ?? [] as $sql) {
            if (preg_match("/^ALTER\s+TABLE\s+`(\w+)`\s+DROP\s+(?:PRIMARY\s+KEY|KEY\s+`(\w+)`)/is", $sql, $m)) {
                $table = $m[1];
                $idxName = (isset($m[2]) && $m[2] !== '') ? $m[2] : 'PRIMARY';
                if (isset($removedIndexMap[$table][$idxName])) {
                    $lines[] = $sql . ';';
                }
            } elseif (preg_match("/^ALTER\s+TABLE\s+`(\w+)`\s+DROP\s+CONSTRAINT\s+`(\w+)`/is", $sql, $m)) {
                $lines[] = $sql . ';';
            }
        }

        foreach ($diffSql['DROP_TABLE'] ?? [] as $sql) {
            $name = preg_match('/DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?`?(\w+)`?/i', $sql, $m) ? $m[1] : null;
            if ($name && isset($removedTables[$name])) {
                $lines[] = "-- [HIGH] DROP TABLE `{$name}`";
                $lines[] = $sql . ";";
            }
        }

        foreach (['ADD_VIEW','MODIFY_VIEW','DROP_VIEW','ADD_PROCEDURE','MODIFY_PROCEDURE','DROP_PROCEDURE','ADD_FUNCTION','MODIFY_FUNCTION','DROP_FUNCTION','ADD_TRIGGER','MODIFY_TRIGGER','DROP_TRIGGER','ADD_EVENT','MODIFY_EVENT','DROP_EVENT'] as $type) {
            if (!empty($diffSql[$type])) {
                foreach ($diffSql[$type] as $sql) {
                    if (str_starts_with($type, 'DROP_')) {
                        // DROP_VIEW/PROCEDURE/FUNCTION/TRIGGER/EVENT → generate DROP statement
                        $objType = substr($type, 5); // VIEW, PROCEDURE, FUNCTION, TRIGGER, EVENT
                        $name = preg_match('/`(\w+)`/', $sql, $m) ? $m[1] : '';
                        $sql = "DROP {$objType} IF EXISTS `{$name}`";
                    } elseif ($type === 'MODIFY_VIEW') {
                        // MySQL: CREATE OR REPLACE VIEW for existing views
                        $sql = preg_replace('/^CREATE\s/', 'CREATE OR REPLACE ', $sql);
                    } elseif (in_array($type, ['MODIFY_TRIGGER','MODIFY_FUNCTION','MODIFY_PROCEDURE'])) {
                        // MySQL has no CREATE OR REPLACE for these; DROP + CREATE
                        $name = preg_match('/`(\w+)`/', $sql, $m) ? $m[1] : '';
                        $objType = str_replace('MODIFY_', '', $type); // TRIGGER, FUNCTION, PROCEDURE
                        $sql = "DROP {$objType} IF EXISTS `{$name}`;\n{$sql}";
                    } elseif ($type === 'MODIFY_EVENT') {
                        $name = preg_match('/`(\w+)`/', $sql, $m) ? $m[1] : '';
                        $sql = "DROP EVENT IF EXISTS `{$name}`;\n{$sql}";
                    }
                    $lines[] = $sql . ";";
                }
                $lines[] = "";
            }
        }

        if ($useTransaction) {
            $lines[] = "COMMIT;";
        }

        return implode("\n", $lines);
    }
}
