<?php
// src/SqlGen/Generator.php

namespace MySqlSchemaSync\SqlGen;

use MySqlSchemaSync\Config\Connection;
use MySqlSchemaSync\Diff\DiffResult;
use MySqlSchemaSync\Diff\StructSyncAdapter;

class Generator
{
    public function __construct(
        private Connection $source,
        private Connection $target,
        private StructSyncAdapter $adapter,
    ) {}

    public function generate(DiffResult $diff, bool $useTransaction = true): string
    {
        $diffSql = $this->adapter->getDiffSql();
        $selectedTables = array_flip(array_column($diff->newTables, 'name'));
        $removedTables = array_flip(array_column($diff->removedTables, 'name'));

        $changedMap = [];
        foreach ($diff->changedTables as $t) {
            $changedMap[$t['name']] = $t;
        }
        $newIndexMap = [];
        foreach ($diff->newIndexes as $i) {
            $newIndexMap[$i['table']][$i['name']] = true;
        }
        $removedIndexMap = [];
        foreach ($diff->removedIndexes as $i) {
            $removedIndexMap[$i['table']][$i['name']] = true;
        }

        $lines = [];
        $lines[] = "-- Auto-generated by MySQL SchemaSync PHP Edition";
        $lines[] = "-- Source: {$this->source->name} ({$this->source->database})";
        $lines[] = "-- Target: {$this->target->name} ({$this->target->database})";
        $lines[] = "-- Generated at: " . date('Y-m-d H:i:s');
        $lines[] = "";

        if ($useTransaction) {
            $lines[] = "START TRANSACTION;";
            $lines[] = "";
        }

        foreach ($diffSql['ADD_TABLE'] ?? [] as $sql) {
            $name = preg_match('/CREATE\s+TABLE\s+`?(\w+)`?/i', $sql, $m) ? $m[1] : null;
            if ($name && isset($selectedTables[$name])) {
                $lines[] = "-- [SAFE] CREATE TABLE `{$name}`";
                $lines[] = rtrim($sql, ';') . ";";
                $lines[] = "";
            }
        }

        foreach ($diffSql['MODIFY_FIELD'] ?? [] as $table => $fields) {
            if (!isset($changedMap[$table])) continue;
            $t = $changedMap[$table];
            $lines[] = "-- === 变更表: {$table} === [{$t['risk']}]";
            foreach ($fields as $col => $def) {
                $lines[] = "ALTER TABLE `{$table}` MODIFY {$def};";
            }
            $lines[] = "";
        }

        foreach ($diffSql['ADD_FIELD'] ?? [] as $table => $fields) {
            if (!isset($changedMap[$table])) continue;
            $lines[] = "-- === 新增列: {$table} ===";
            foreach ($fields as $col => $def) {
                $lines[] = "ALTER TABLE `{$table}` ADD {$def};";
            }
            $lines[] = "";
        }

        foreach ($diffSql['DROP_FIELD'] ?? [] as $table => $fields) {
            if (!isset($changedMap[$table])) continue;
            $lines[] = "-- === 删除列: {$table} ===";
            foreach ($fields as $col => $def) {
                $lines[] = "ALTER TABLE `{$table}` DROP COLUMN `{$col}`;";
            }
            $lines[] = "";
        }

        foreach ($diffSql['ADD_CONSTRAINT'] ?? [] as $table => $constraints) {
            if (!isset($newIndexMap[$table])) continue;
            foreach ($constraints as $c) {
                if (preg_match('/`(\w+)`/', $c, $nm) && isset($newIndexMap[$table][$nm[1]])) {
                    $lines[] = "ALTER TABLE `{$table}` ADD {$c};";
                }
            }
        }

        foreach ($diffSql['DROP_CONSTRAINT'] ?? [] as $table => $constraints) {
            if (!isset($removedIndexMap[$table])) continue;
            foreach ($constraints as $c) {
                if (preg_match('/`(\w+)`/', $c, $nm) && isset($removedIndexMap[$table][$nm[1]])) {
                    $lines[] = $c;
                }
            }
        }

        foreach ($diffSql['DROP_TABLE'] ?? [] as $sql) {
            $name = preg_match('/DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?`?(\w+)`?/i', $sql, $m) ? $m[1] : null;
            if ($name && isset($removedTables[$name])) {
                $lines[] = "-- [HIGH] DROP TABLE `{$name}`";
                $lines[] = $sql . ";";
            }
        }

        foreach (['ADD_VIEW', 'DROP_VIEW', 'ADD_PROCEDURE', 'DROP_PROCEDURE', 'ADD_FUNCTION', 'DROP_FUNCTION', 'ADD_TRIGGER', 'DROP_TRIGGER', 'ADD_EVENT', 'DROP_EVENT'] as $type) {
            if (!empty($diffSql[$type])) {
                foreach ($diffSql[$type] as $sql) {
                    $lines[] = $sql . ";";
                }
                $lines[] = "";
            }
        }

        if ($useTransaction) {
            $lines[] = "COMMIT;";
        }

        return implode("\n", $lines);
    }
}
